cat8kv:
  hostname: "10.10.20.48"
  port: 22
  username: "developer"
  password: "C1sco12345"
  groups:
    - cisco_iosxe

iosxrv:
  hostname: "10.10.20.35"
  port: 22
  username: "developer"
  password: "C1sco12345"
  groups:
    - cisco_iosxr
  connection_options:
    netmiko:
      extras:
        disabled_algorithms:
          pubkeys:
            - rsa-sha2-256
            - rsa-sha2-512

nexus9k:
  hostname: "10.10.20.40"
  port: 22
  username: "admin"
  password: "RG!_Yw200"
  groups:
    - cisco_nxos
